<a href="https://colab.research.google.com/github/Saiful-2/notebooks/blob/main/hiring_salary_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Salary Prediction using Machine Learning (Hiring Dataset)

## Step 1: Import Libraries

In [1]:
import pandas as pd
import numpy as np
import math

from sklearn.linear_model import LinearRegression

## Step 2: Load Dataset

In [2]:
url = "https://raw.githubusercontent.com/Saiful-2/datasets/main/hiring.csv"

df = pd.read_csv(url)

df

,experience,test_score(out of 10),interview_score(out of 10),salary($)
0,NaN,8.0,9,50000
1,NaN,8.0,6,45000
2,five,6.0,7,60000
3,two,10.0,10,65000
4,seven,9.0,6,70000
5,three,7.0,10,62000
6,ten,NaN,7,72000
7,eleven,7.0,8,80000


## Step 3: Fill Missing Experience Values

In [3]:
df.experience = df.experience.fillna("zero")

## Step 4: Convert Text into Numbers

In [4]:
experience_mapping = {
    "zero": 0,
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10
}

In [5]:
df.experience = df.experience.map(experience_mapping)

## Step 5: Fill Missing Test Score

In [6]:
median_test_score = math.floor(df['test_score(out of 10)'].median())

df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)

## Step 6: Check Dataset Again

In [7]:
df

,experience,test_score(out of 10),interview_score(out of 10),salary($)
0,0.0,8.0,9,50000
1,0.0,8.0,6,45000
2,5.0,6.0,7,60000
3,2.0,10.0,10,65000
4,7.0,9.0,6,70000
5,3.0,7.0,10,62000
6,10.0,8.0,7,72000
7,NaN,7.0,8,80000


## Step 7: Check Missing Values

In [8]:
df.isnull().sum()

,0
experience,1
test_score(out of 10),0
interview_score(out of 10),0
salary($),0


## Step 8: Features and Target

In [9]:
X = df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]

y = df['salary($)']

## Step 9: Train Model

In [10]:
model = LinearRegression()

# Impute NaN values in the 'experience' column of X with its median
X_imputed = X.copy()
X_imputed['experience'] = X_imputed['experience'].fillna(X_imputed['experience'].median())

model.fit(X_imputed, y)

LinearRegression()

## Step 10: Prediction

### Predict Salary for New Candidates
##Candidate 1
Information
Experience = 2 years
Test Score = 9
Interview Score = **6**

In [11]:
model.predict([[2, 9, 6]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([54224.42370639])

Candidate 2
Information
Experience = 12 years
Test Score = 10
Interview Score = 10

In [12]:
model.predict([[12, 10, 10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88743.8888502])

## Step 11: Model Coefficients

In [13]:
model.coef_

array([2529.45887597,  -15.59997214, 2310.11908907])

## Step 12: Intercept

In [14]:
model.intercept_

np.float64(35445.19116930149)